package com.anjing.orderops.enums;

public enum AuditEventType {
    ORDER_QUERIED,
    PLAN_CREATED,
    IDEMPOTENCY_REPLAYED,
    APPROVAL_CREATED,
    APPROVAL_CONFIRMED,
    APPROVAL_REJECTED,
    TOOL_CALL_STARTED,
    TOOL_CALL_SUCCEEDED,
    TOOL_CALL_FAILED,
    EXECUTION_SUCCEEDED,
    EXECUTION_FAILED,
    COMPENSATION_CREATED,
    COMPENSATION_RETRIED,
    COMPENSATION_SUCCEEDED,
    COMPENSATION_FAILED
}
